In [6]:
import torch
from holo.test_functions.closed_form import Ehrlich
from holo.optim import DiscreteEvolution

test_fn = Ehrlich(negate=True)
print(f"Desired motif: {test_fn.motifs[0]}")
print(f"Desired motif spacing: {test_fn.spacings[0]}")
print(f"Optimal value: {test_fn.optimal_value}")
initial_solution = test_fn.initial_solution()
vocab = list(range(test_fn.num_states))

tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487],
        [ 0.6920, -0.3160, -2.1152,  0.3223, -0.1577],
        [ 1.4437,  0.2660,  0.1665,  0.8744, -0.1435],
        [-0.1116, -0.6136,  1.2590,  2.0050,  0.0537],
        [ 0.6181, -0.4128, -0.8411, -2.3160, -0.1023]])
tensor([[0.0157, 0.0149, 0.0905, 0.0628, 0.8161],
        [0.5565, 0.0741, 0.0020, 0.2657, 0.1017],
        [0.6516, 0.0618, 0.0507, 0.2087, 0.0273],
        [0.0115, 0.0042, 0.1778, 0.7905, 0.0160],
        [0.7038, 0.0895, 0.0380, 0.0020, 0.1666]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])
Desired motif: tensor([3, 3, 3])
Desired motif spacing: tensor([2, 3])
Optimal value: -1.0


In [7]:
params = [
    torch.nn.Parameter(
        initial_solution.float(),
    )
]

optimizer = DiscreteEvolution(
    params,
    vocab,
    mutation_prob=1/test_fn.dim,
    recombine_prob=1/test_fn.dim,
    num_particles=1024,
    survival_quantile=0.01
)

print(f"\nInitial solution: {params[0].data}")
print("\nOptimizing...")
for _ in range(4):
    loss = optimizer.step(lambda x: test_fn(x[0]))
    print(f"loss: {loss}")
print(f"\nFinal solution: {params[0].data}")


Initial solution: tensor([2., 3., 3., 3., 3., 3., 3.])

Optimizing...
loss: -1.0
loss: -1.0
loss: -1.0
loss: -1.0

Final solution: tensor([3., 3., 3., 4., 3., 3., 3.])


In [5]:
params

[Parameter containing:
 tensor([2., 3., 3., 3., 3., 3., 3.], requires_grad=True)]