In [1]:
import torch
from holo.test_functions.closed_form import Ehrlich

/home/ghandill/miniconda3/envs/holo/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [24]:
test_fn_params = {
    "num_states": 4,
    "dim": 64,
    "num_motifs": 4,
    "motif_length": 4,
    "quantization": 4,
    "random_seed": 0,
}

device = torch.device("cuda")

test_fn = Ehrlich(**test_fn_params, negate=False)

seq_len = test_fn_params["dim"]
num_tokens = test_fn_params["num_states"]
start_token = num_tokens

model_params = {
    "embedding_dim": 32,
    "num_heads": 4,
    "output_dim": test_fn_params["num_states"],
    "vocab_size": test_fn_params["num_states"] + 2,
}

test_fn.to(device, torch.float)


tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473]])
tensor([[0.0855, 0.0811, 0.4923, 0.3412],
        [0.5462, 0.3992, 0.0532, 0.0015],
        [0.3256, 0.0137, 0.3442, 0.3165],
        [0.0550, 0.5145, 0.4040, 0.0264]])
tensor([[ True,  True, False,  True],
        [ True,  True,  True, False],
        [False,  True,  True,  True],
        [ True, False,  True,  True]])


Ehrlich(num_states=4, dim=64, num_motifs=4, motifs=[motif_0: [0, 3, 2, 2], motif_1: [2, 3, 0, 3], motif_2: [2, 3, 0, 3], motif_3: [2, 3, 2, 2]], spacings=[spacing_0: [1, 3, 10], spacing_1: [5, 5, 4], spacing_2: [4, 9, 1], spacing_3: [2, 3, 9]], quantization=4, noise_std=0.0, negate=False, random_seed=0)

In [25]:
from lib.training import sample_sequences
from lib.NewSequenceModel import SequenceModel

In [26]:
q = SequenceModel(**model_params, seq_len=test_fn_params["dim"])

In [27]:
fixed_state_batch = sample_sequences(
    q=q,  # Use a random policy (or disable Q-function dependence)
    epsilon=1.0,  # Ensure full exploration if required
    batch_size=64,
    start_token=start_token,
    seq_len=seq_len,
    num_states=num_tokens,
    device=device
)

In [28]:
fixed_state_batch.shape

fixed_state_batch

tensor([[3, 0, 3,  ..., 1, 3, 1],
        [0, 2, 1,  ..., 0, 3, 3],
        [2, 2, 1,  ..., 1, 2, 0],
        ...,
        [0, 1, 2,  ..., 1, 3, 3],
        [3, 3, 0,  ..., 2, 3, 3],
        [2, 1, 0,  ..., 0, 0, 0]], device='cuda:0')

In [29]:
test_fn.to(device, torch.float)
test_fn(fixed_state_batch)

tensor([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       device='cuda:0')

In [30]:
sum(test_fn(fixed_state_batch))

tensor(-inf, device='cuda:0')

Previous function

In [110]:
test_fn_params = {
    "num_states": 32,
    "dim": 64,
    "num_motifs": 4,
    "motif_length": 4,
    "quantization": 4,
}


In [111]:
test_fn = Ehrlich(negate=False, **test_fn_params)

In [112]:
test_fn(fixed_state_batch)

tensor([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf])

Last Holo settings

test_fn_params = {
    "num_states": 5,
    "dim": 32,
    "num_motifs": 4,
    "motif_length": 4,
    "quantization": 4,
    "random_seed": 0,
}

test_fn = Ehrlich(**test_fn_params, negate=False)
test_fn.to(device, torch.float)
