In [3]:
import torch
from holo.test_functions.closed_form import Ehrlich

/home/ghandill/miniconda3/envs/holo/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
test_fn_params = {
    "num_states": 4,
    "dim": 64,
    "num_motifs": 1,
    "motif_length": 5,
    "random_seed": 0,
}

# num_states = 4
# num_steps = 5
# motif_length = 5
# num_motifs = 1
# random_seed = 0
# ehrlich = Ehrlich(
#     num_states=num_states,
#     dim=num_steps,
#     num_motifs=num_motifs,
#     motif_length=motif_length,
#     random_seed=random_seed,
# )

device = torch.device("cuda")

test_fn = Ehrlich(**test_fn_params, negate=False)

seq_len = test_fn_params["dim"]
num_tokens = test_fn_params["num_states"]
start_token = num_tokens

model_params = {
    "embedding_dim": 32,
    "num_heads": 4,
    "output_dim": test_fn_params["num_states"],
    "vocab_size": test_fn_params["num_states"] + 2,
}

test_fn.to(device, torch.float)


TypeError: Ehrlich.__init__() got an unexpected keyword argument 'num_steps'. Did you mean 'num_states'?

In [ ]:
from lib.training_utils import sample_sequences
from lib.SequenceModel import SequenceModel


In [24]:
q = SequenceModel(**model_params, seq_len=test_fn_params["dim"])

KeyError: 'dim'

In [19]:
fixed_state_batch = sample_sequences(
    q=q,  # Use a random policy (or disable Q-function dependence)
    epsilon=1.0,  # Ensure full exploration if required
    batch_size=64,
    start_token=start_token,
    seq_len=seq_len,
    num_states=num_tokens,
    device=device
)

In [20]:
fixed_state_batch.shape

fixed_state_batch

tensor([[3, 1, 0,  ..., 0, 0, 3],
        [2, 3, 1,  ..., 2, 3, 2],
        [2, 0, 0,  ..., 3, 2, 2],
        ...,
        [2, 2, 1,  ..., 0, 1, 2],
        [1, 3, 1,  ..., 3, 2, 1],
        [0, 1, 0,  ..., 0, 1, 2]], device='cuda:0')

In [21]:
test_fn.to(device, torch.float)
test_fn(fixed_state_batch)

tensor([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       device='cuda:0')

In [22]:
sum(test_fn(fixed_state_batch))

tensor(-inf, device='cuda:0')

Previous function

In [110]:
test_fn_params = {
    "num_states": 32,
    "dim": 64,
    "num_motifs": 4,
    "motif_length": 4,
    "quantization": 4,
}


In [111]:
test_fn = Ehrlich(negate=False, **test_fn_params)

In [112]:
test_fn(fixed_state_batch)

tensor([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf])

Last Holo settings

test_fn_params = {
    "num_states": 5,
    "dim": 32,
    "num_motifs": 4,
    "motif_length": 4,
    "quantization": 4,
    "random_seed": 0,
}

test_fn = Ehrlich(**test_fn_params, negate=False)
test_fn.to(device, torch.float)
